version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
    - ./vote:/app
    ports:
    - "5000:80"

  process-vote:
    build: ./process-vote
    restart: always

  db:
    image: postgres:9.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  result:
    build: ./result
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
